name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送以 'v' 开头的标签时触发，如 v1.0.0, v2.1.3

jobs:
  build:
    name: Build for multiple platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            suffix: .exe
            name: windows-amd64
          - goos: windows
            goarch: arm64
            suffix: .exe
            name: windows-arm64
          - goos: darwin
            goarch: amd64
            suffix: ""
            name: macos-amd64
          - goos: darwin
            goarch: arm64
            suffix: ""
            name: macos-arm64
          - goos: linux
            goarch: amd64
            suffix: ""
            name: linux-amd64
          - goos: linux
            goarch: arm64
            suffix: ""
            name: linux-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Install build dependencies for Linux
      if: matrix.goos == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib libc6-dev
        # 安装 Fyne 所需的依赖
        sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: Install cross-compilation tools for Windows
      if: matrix.goos == 'windows'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        # 设置交叉编译环境
        if [ "${{ matrix.goos }}" = "windows" ]; then
          if [ "${{ matrix.goarch }}" = "amd64" ]; then
            export CC=x86_64-w64-mingw32-gcc
            export CXX=x86_64-w64-mingw32-g++
          else
            export CC=aarch64-w64-mingw32-gcc
            export CXX=aarch64-w64-mingw32-g++
          fi
        fi
        
        # 构建二进制文件
        OUTPUT_NAME="Cursor_Windsurf_Reset-${{ matrix.name }}${{ matrix.suffix }}"
        go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o "${OUTPUT_NAME}" main.go
        
        # 验证文件是否创建成功
        if [ -f "${OUTPUT_NAME}" ]; then
          echo "✅ 构建成功: ${OUTPUT_NAME}"
          ls -la "${OUTPUT_NAME}"
        else
          echo "❌ 构建失败: ${OUTPUT_NAME}"
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Cursor_Windsurf_Reset-${{ matrix.name }}
        path: Cursor_Windsurf_Reset-${{ matrix.name }}${{ matrix.suffix }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Display structure of downloaded files
      run: |
        echo "📁 下载的文件结构:"
        find . -name "Cursor_Windsurf_Reset-*" -type f | sort

    - name: Prepare release files
      run: |
        mkdir -p release-files
        
        # 移动所有构建的二进制文件到 release-files 目录
        find . -name "Cursor_Windsurf_Reset-*" -type f -executable -o -name "*.exe" | while read file; do
          if [ -f "$file" ]; then
            cp "$file" release-files/
            echo "✅ 复制文件: $file -> release-files/"
          fi
        done
        
        # 复制配置文件和文档
        cp cleaner_config.json release-files/
        cp README.md release-files/
        
        echo "📦 准备发布的文件:"
        ls -la release-files/

    - name: Generate release notes
      id: release_notes
      run: |
        TAG_NAME=${{ github.ref_name }}
        echo "🎉 Cursor & Windsurf 重置工具 ${TAG_NAME}" > release_notes.md
        echo "" >> release_notes.md
        echo "## 📦 下载说明" >> release_notes.md
        echo "" >> release_notes.md
        echo "请根据您的操作系统下载对应的版本：" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Windows 用户" >> release_notes.md
        echo "- **Windows x64**: \`Cursor_Windsurf_Reset-windows-amd64.exe\`" >> release_notes.md
        echo "- **Windows ARM64**: \`Cursor_Windsurf_Reset-windows-arm64.exe\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "### macOS 用户" >> release_notes.md
        echo "- **Intel Mac**: \`Cursor_Windsurf_Reset-macos-amd64\`" >> release_notes.md
        echo "- **Apple Silicon (M1/M2)**: \`Cursor_Windsurf_Reset-macos-arm64\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Linux 用户" >> release_notes.md
        echo "- **Linux x64**: \`Cursor_Windsurf_Reset-linux-amd64\`" >> release_notes.md
        echo "- **Linux ARM64**: \`Cursor_Windsurf_Reset-linux-arm64\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "## 🚀 使用方法" >> release_notes.md
        echo "" >> release_notes.md
        echo "1. 下载对应平台的可执行文件" >> release_notes.md
        echo "2. 下载 \`cleaner_config.json\` 配置文件（可选）" >> release_notes.md
        echo "3. 双击运行（Windows）或在终端中执行" >> release_notes.md
        echo "4. 详细使用说明请参考 \`README.md\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "## ⚠️ 注意事项" >> release_notes.md
        echo "" >> release_notes.md
        echo "- 使用前请备份重要数据" >> release_notes.md
        echo "- 确保 Cursor 和 Windsurf 应用已完全关闭" >> release_notes.md
        echo "- 首次运行可能需要管理员权限" >> release_notes.md
        echo "- macOS 和 Linux 用户可能需要添加执行权限：\`chmod +x Cursor_Windsurf_Reset-*\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "## 🔧 技术信息" >> release_notes.md
        echo "" >> release_notes.md
        echo "- **版本**: ${TAG_NAME}" >> release_notes.md
        echo "- **构建时间**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> release_notes.md
        echo "- **Go 版本**: 1.21" >> release_notes.md
        echo "- **GUI 框架**: Fyne v2" >> release_notes.md
        
        echo "📝 生成的发布说明:"
        cat release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: "Cursor & Windsurf 重置工具 ${{ github.ref_name }}"
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: |
          release-files/*
        generate_release_notes: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release summary
      run: |
        echo "🎉 发布完成！" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 📦 发布信息" >> $GITHUB_STEP_SUMMARY
        echo "- **标签**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **发布时间**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 🔗 链接" >> $GITHUB_STEP_SUMMARY
        echo "- [查看发布页面](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})" >> $GITHUB_STEP_SUMMARY
        echo "- [下载文件](https://github.com/${{ github.repository }}/releases/latest)" >> $GITHUB_STEP_SUMMARY